//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GörselP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int ID { get; set; }
        public string KullanciAd { get; set; }
        public string Şifre { get; set; }
        public Nullable<bool> personal { get; set; }
        public Nullable<bool> rezirvasiyon { get; set; }
        public Nullable<bool> sipariş { get; set; }
        public Nullable<bool> menüitem { get; set; }
        public Nullable<bool> kullanıcılar { get; set; }
        public Nullable<bool> fatura { get; set; }
    }
}
