//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GörselP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menüİtem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menüİtem()
        {
            this.Sipariş = new HashSet<Sipariş>();
        }
    
        public int ID { get; set; }
        public string ÜrünAd { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public int ID_Menü { get; set; }
    
        public virtual Menü Menü { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sipariş> Sipariş { get; set; }
    }
}
