//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GörselP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestorantOEntities2 : DbContext
    {
        public RestorantOEntities2()
            : base("name=RestorantOEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Masa> Masas { get; set; }
        public virtual DbSet<Menü> Menü { get; set; }
        public virtual DbSet<Menüİtem> Menüİtem { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<Rezervasiyon> Rezervasiyons { get; set; }
        public virtual DbSet<Sipariş> Sipariş { get; set; }
    }
}
