//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GörselP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasiyon
    {
        public int ID { get; set; }
        public System.DateTime RezervasiyonTarihi { get; set; }
        public int Masa_ID { get; set; }
        public string MüşteriAd { get; set; }
        public string TelefonNO { get; set; }
    
        public virtual Masa Masa { get; set; }
    }
}
