//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GörselP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipariş
    {
        public Nullable<int> Sipariş_No { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<double> Toplam { get; set; }
        public Nullable<int> ID_Masa { get; set; }
        public Nullable<int> ID_Menüitem { get; set; }
        public int ID { get; set; }
    
        public virtual Masa Masa { get; set; }
        public virtual Menüİtem Menüİtem { get; set; }
    }
}
